
#server:
#  port: 80
#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://47.100.117.203:3306/blog?serverTimezone=UTC
#      username: root
#      password: Daimeng357.


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ych3362632
    type:
  application:
    name: blog_ychhh
  main:
    banner-mode: off


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      # 配置表明的前缀
      table-prefix: ms_



#  config-location: classpath:mybatis-config.xml


logging:
  level:
    root: debug
